# Please complete step 5.1 and 5.2 before running this playbook
# For step 5.2 please use the command:
#      sudo vi /etc/ansible/facts.d/custom.fact


---
- name: Install Apache and starts the service
  hosts: webserver
  tasks:
    - name: Install the required package
      dnf:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['package'] }}"
        state: latest

    - name: Start the service
      service:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['general']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['general']['enabled'] }}"
